/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

%{C++
#define MMS_SERVICE_CID { 0xa94b949f, 0xe5c3, 0x48a3, { 0x84, 0x16, 0x13, 0xb9, 0xfa, 0x0e, 0x3b, 0xff } }
#define MMS_SERVICE_CONTRACTID "@mozilla.org/mms/mmsservice;1"
%}

[scriptable, uuid(dde303bb-9a70-4ccc-adfd-0adf4e1a697a)]
interface nsIMmsService : nsISupports
{
  boolean        hasSupport();
};
